### ISSUE TITLE
[Bug] Condition on the shape of feature matrix is wrong

### ISSUE THREAD

**Issue by JulienPeloton** [b-biswas/kndetect#17]
In features.py, there is a condition to flag empty feature matrix:

https://github.com/b-biswas/kndetect/blob/6f4720c7d8203e1d50f549017bbbfc907390c909/kndetect/predict.py#L85-L88

But the check should not be done on the length, as in Python this only takes the first dimension:

```python
In [1]: import numpy as np

In [2]: array = np.zeros((5, 10))

In [3]: len(array) # current, wrong
Out[3]: 5

In [4]: np.shape(array) # better
Out[4]: (5, 10)
```

Possible fixes:

```python
# checking 1st dimension only
if len(features_df[filtered_indices]) == 0:

# checking full shape
if np.shape(features_df[filtered_indices]) == (0, len(feature_col_names)):
```

**Comment by b-biswas** [comment]
Thanks for pointing this out!
Should be fixed now!

**Comment by JulienPeloton** [comment]
Thanks!
